### ISSUE TITLE
remove cards with no positions

### ISSUE THREAD

**Issue by Enjoy2Live** [dev-launchers/Dev-Recruiters#7]
Currently we have cards of products/ideas/projects with no positions available. those should not be showing in the aggregator page.
@mdinacer has made an outstanding PR [#2] that implements the cards and the filtering but it was missing this minor change.
![image](https://user-images.githubusercontent.com/27841994/160143832-3e5c2c12-920a-443b-8630-90ba9960a382.png)

**Comment by mdinacer** [comment]
Fixed that issue by adding a filter condition upon data fetching
